// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as InputStyles$Codex from "./InputStyles.bs.js";

function Input(Props) {
  var value = Props.value;
  var onChange = Props.onChange;
  var type_ = Props.type_;
  var isValid = Props.isValid;
  var placeholder = Props.placeholder;
  var required = Props.required;
  var readOnly = Props.readOnly;
  return React.createElement("input", {
              className: InputStyles$Codex.input(isValid),
              placeholder: placeholder,
              readOnly: readOnly,
              required: required,
              type: type_,
              value: value,
              onChange: onChange
            });
}

var make = Input;

export {
  make ,
  
}
/* react Not a pure module */
