// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Colors$Savvy from "../../styles/Colors.bs.js";
import * as Css_AtomicTypes from "bs-css/src/Css_AtomicTypes.js";

var button = Css.style(/* :: */[
      Css.height(Css.px(55)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* :: */[
          Css.border(Css.px(0), /* none */-922086728, Css.transparent),
          /* :: */[
            Css.maxWidth(Css.px(300)),
            /* :: */[
              Css.margin(Css.px(25)),
              /* :: */[
                Css.borderRadius(Css.px(4)),
                /* :: */[
                  Css.backgroundColor(Css_AtomicTypes.Color.hex(Colors$Savvy.red)),
                  /* :: */[
                    Css.boxShadows(/* :: */[
                          Css.Shadow.box(undefined, Css.px(1), Css.px(3), undefined, undefined, Css.rgba(0, 0, 0, 0.12)),
                          /* :: */[
                            Css.Shadow.box(undefined, Css.px(1), Css.px(2), undefined, undefined, Css.rgba(0, 0, 0, 0.24)),
                            /* [] */0
                          ]
                        ]),
                    /* :: */[
                      Css.focus(/* :: */[
                            Css.outline(Css.px(0), /* none */-922086728, Css.transparent),
                            /* [] */0
                          ]),
                      /* :: */[
                        Css.fontSize(Css.px(16)),
                        /* :: */[
                          Css.color(Css.white),
                          /* :: */[
                            Css.cursor(/* pointer */-786317123),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  button ,
  
}
/* button Not a pure module */
