// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function CountDown(Props) {
  var match = React.useState((function () {
          return 1;
        }));
  var setCount = match[1];
  var count = match[0];
  var updateCounter = function (param) {
    return Curry._1(setCount, (function (state) {
                  return state + 1 | 0;
                }));
  };
  var timer = setInterval(updateCounter, 1000);
  React.useEffect((function () {
          if (count >= 5) {
            clearInterval(timer);
          }
          return (function (param) {
                    clearInterval(timer);
                    return /* () */0;
                  });
        }), /* array */[count]);
  return React.createElement("div", undefined, "Counter " + String(count));
}

var make = CountDown;

export {
  make ,
  
}
/* react Not a pure module */
