// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Stream from "bs-platform/lib/es6/stream.js";
import * as Button$Savvy from "../Button/Button.bs.js";
import * as Question$Savvy from "../Question/Question.bs.js";
import * as QuizContext$Savvy from "../../context/QuizContext.bs.js";
import * as QuestionCount$Savvy from "../QuestionCount/QuestionCount.bs.js";
import * as QuestionStyles$Savvy from "../Question/QuestionStyles.bs.js";

function Questions(Props) {
  var match = React.useState((function () {
          return ;
        }));
  var setCurrentQuestion = match[1];
  var match$1 = React.useState((function () {
          return 0;
        }));
  var setQuestionCount = match$1[1];
  var quizContext = QuizContext$Savvy.useQuiz(/* () */0);
  var nextQuestion = function (param) {
    var question;
    try {
      question = Stream.next(quizContext[/* state */0][/* quizStream */2]);
    }
    catch (exn){
      if (exn === Stream.Failure) {
        console.log("No questions left");
        return /* () */0;
      } else {
        throw exn;
      }
    }
    Curry._1(setCurrentQuestion, (function (param) {
            return question;
          }));
    return Curry._1(setQuestionCount, (function (count) {
                  return count + 1 | 0;
                }));
  };
  var totalQuestions = quizContext[/* state */0][/* questions */1].length;
  React.useEffect((function () {
          nextQuestion(/* () */0);
          return ;
        }), /* array */[quizContext[/* state */0][/* quizStream */2]]);
  var match$2 = quizContext[/* state */0][/* fetchingQuestions */7];
  if (match$2) {
    return React.createElement("div", undefined, "Loading...");
  } else {
    return React.createElement("div", {
                className: QuestionStyles$Savvy.questions
              }, React.createElement(QuestionCount$Savvy.make, {
                    count: match$1[0],
                    total: totalQuestions
                  }), React.createElement(Question$Savvy.make, {
                    currentQuestion: match[0]
                  }), React.createElement(Button$Savvy.make, {
                    text: "Next",
                    type_: "button",
                    onClick: (function (param) {
                        return nextQuestion(/* () */0);
                      }),
                    disabled: false
                  }));
  }
}

var make = Questions;

export {
  make ,
  
}
/* react Not a pure module */
