// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Stream from "bs-platform/lib/es6/stream.js";
import * as Question$Savvy from "../Question/Question.bs.js";

function Questions(Props) {
  var questionStream = Props.questionStream;
  var match = React.useState((function () {
          return ;
        }));
  var setCurrentQuestion = match[1];
  var nextQuestion = function (param) {
    var question;
    try {
      question = Stream.next(questionStream);
    }
    catch (exn){
      if (exn === Stream.Failure) {
        console.log("No questions left");
        return /* () */0;
      } else {
        throw exn;
      }
    }
    return Curry._1(setCurrentQuestion, (function (param) {
                  return question;
                }));
  };
  React.useEffect((function () {
          nextQuestion(/* () */0);
          return ;
        }), ([]));
  return React.createElement("div", undefined, React.createElement(Question$Savvy.make, {
                  currentQuestion: match[0],
                  nextQuestion: nextQuestion
                }));
}

var make = Questions;

export {
  make ,
  
}
/* react Not a pure module */
