// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Colors$Savvy from "../../styles/Colors.bs.js";
import * as Css_AtomicTypes from "bs-css/src/Css_AtomicTypes.js";

var $$process = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.height(Css.px(50)),
        /* :: */[
          Css.border(Css.px(2), Css.solid, Css_AtomicTypes.Color.hex(Colors$Savvy.lightblue)),
          /* :: */[
            Css.borderRadius(Css.px(10)),
            /* [] */0
          ]
        ]
      ]
    ]);

function processBar(processStatus) {
  return Css.style(/* :: */[
              Css.display(Css.inlineBlock),
              /* :: */[
                Css.width(Css.pct(processStatus)),
                /* :: */[
                  Css.height(Css.pct(100)),
                  /* :: */[
                    Css.borderRadius(Css.px(8)),
                    /* :: */[
                      Css.backgroundColor(Css_AtomicTypes.Color.hex(Colors$Savvy.darkerIndigo)),
                      /* :: */[
                        Css.transition(200, 0, Css.easeInOut, "width"),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

export {
  $$process ,
  processBar ,
  
}
/* process Not a pure module */
