// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ProcessStyles$Savvy from "./ProcessStyles.bs.js";

function Process(Props) {
  var count = Props.count;
  var totalQuestions = Props.totalQuestions;
  var total = count / totalQuestions;
  return React.createElement("div", {
              className: ProcessStyles$Savvy.$$process
            }, React.createElement("span", {
                  className: ProcessStyles$Savvy.processBar(total * 100)
                }));
}

var make = Process;

export {
  make ,
  
}
/* react Not a pure module */
