// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function decode(json) {
  return /* record */[
          /* response_code */Json_decode.field("response_code", Json_decode.$$int, json),
          /* response_message */Json_decode.field("response_message", Json_decode.string, json),
          /* token */Json_decode.field("token", Json_decode.string, json)
        ];
}

var RequestToken = {
  decode: decode
};

function decode$1(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json)
        ];
}

var Category = {
  decode: decode$1
};

function decode$2(json) {
  return /* record */[/* trivia_categories */Json_decode.field("trivia_categories", (function (param) {
                  return Json_decode.list(decode$1, param);
                }), json)];
}

var Categories = {
  decode: decode$2
};

export {
  RequestToken ,
  Category ,
  Categories ,
  
}
/* No side effect */
