// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as APIDecode$Savvy from "../../apiDecode/APIDecode.bs.js";

function Categories(Props) {
  var children = Props.children;
  var match = React.useState((function () {
          return /* LoadingCategories */0;
        }));
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          fetch("https://opentdb.com/api_category.php").then((function (prim) {
                      return prim.json();
                    })).then((function (json) {
                    var response = APIDecode$Savvy.Categories.decode(json);
                    Curry._1(setState, (function (_prevState) {
                            return /* LoadedCategories */[response[/* trivia_categories */0]];
                          }));
                    return Promise.resolve(/* () */0);
                  })).catch((function (_err) {
                  Curry._1(setState, (function (_prevState) {
                          return /* Error */1;
                        }));
                  return Promise.resolve(/* () */0);
                }));
          return ;
        }), ([]));
  if (typeof state === "number") {
    if (state !== 0) {
      return "Error";
    } else {
      return "Loading Categories";
    }
  } else {
    return Curry._1(children, state[0]);
  }
}

var initialState = /* LoadingCategories */0;

var make = Categories;

export {
  initialState ,
  make ,
  
}
/* react Not a pure module */
