// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as SelectStyles$Savvy from "./SelectStyles.bs.js";

function Select(Props) {
  var options = Props.options;
  var onChange = Props.onChange;
  return React.createElement("select", {
              className: SelectStyles$Savvy.select,
              onChange: (function ($$event) {
                  return Curry._1(onChange, $$event.target.value);
                })
            }, $$Array.of_list(List.map((function (option) {
                        return React.createElement("option", {
                                    key: option[/* value */0],
                                    value: option[/* value */0]
                                  }, option[/* label */1]);
                      }), options)));
}

var make = Select;

export {
  make ,
  
}
/* react Not a pure module */
