// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Colors$Savvy from "../../styles/Colors.bs.js";
import * as Css_AtomicTypes from "bs-css/src/Css_AtomicTypes.js";

var select = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.height(Css.px(50)),
        /* :: */[
          Css.margin4(Css.px(5), Css.px(0), Css.px(5), Css.px(0)),
          /* :: */[
            Css.padding(Css.px(20)),
            /* :: */[
              Css.border(Css.px(1), /* solid */12956715, Css_AtomicTypes.Color.hex(Colors$Savvy.gray)),
              /* :: */[
                Css.borderRadius(Css.px(8)),
                /* :: */[
                  Css.boxShadow(/* none */-922086728),
                  /* :: */[
                    Css.fontSize(Css.px(16)),
                    /* :: */[
                      Css.focus(/* :: */[
                            Css.outline(Css.px(0), /* none */-922086728, Css.transparent),
                            /* [] */0
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  select ,
  
}
/* select Not a pure module */
