// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var category = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* [] */0
      ]
    ]);

export {
  category ,
  
}
/* category Not a pure module */
