// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Colors$Savvy from "../../styles/Colors.bs.js";
import * as Css_AtomicTypes from "bs-css/src/Css_AtomicTypes.js";

var category = Css.style(/* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.textAlign(Css.center),
        /* :: */[
          Css.cursor(/* pointer */-786317123),
          /* :: */[
            Css.hover(/* :: */[
                  Css.backgroundColor(Css_AtomicTypes.Color.hex(Colors$Savvy.red)),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  category ,
  
}
/* category Not a pure module */
