// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function General(Props) {
  return React.createElement("div", undefined, "General Questions");
}

var make = General;

export {
  make ,
  
}
/* react Not a pure module */
