// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function decode(json) {
  return /* record */[
          /* response_code */Json_decode.field("response_code", Json_decode.$$int, json),
          /* response_message */Json_decode.field("response_message", Json_decode.string, json),
          /* token */Json_decode.field("token", Json_decode.string, json)
        ];
}

var RequestToken = {
  decode: decode
};

function decode$1(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json)
        ];
}

var Category = {
  decode: decode$1
};

function decode$2(json) {
  return /* record */[/* trivia_categories */Json_decode.field("trivia_categories", (function (param) {
                  return Json_decode.array(decode$1, param);
                }), json)];
}

var Categories = {
  decode: decode$2
};

function decode$3(json) {
  return /* record */[
          /* category */Json_decode.field("category", Json_decode.string, json),
          /* type_ */Json_decode.field("type", Json_decode.string, json),
          /* difficulty */Json_decode.field("difficulty", Json_decode.string, json),
          /* question */Json_decode.field("question", Json_decode.string, json),
          /* correctAnswer */Json_decode.field("correct_answer", Json_decode.string, json),
          /* incorretAnswers */Json_decode.field("incorrect_answers", (function (param) {
                  return Json_decode.list(Json_decode.string, param);
                }), json)
        ];
}

var CategoryType = {
  decode: decode$3
};

function decode$4(json) {
  return /* record */[
          /* responseCode */Json_decode.field("response_code", Json_decode.$$int, json),
          /* results */Json_decode.field("results", (function (param) {
                  return Json_decode.array(decode$3, param);
                }), json)
        ];
}

var CategoryTypeResult = {
  decode: decode$4
};

export {
  RequestToken ,
  Category ,
  Categories ,
  CategoryType ,
  CategoryTypeResult ,
  
}
/* No side effect */
