// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as HeaderStyles$Savvy from "./HeaderStyles.bs.js";

function Header(Props) {
  return React.createElement("header", {
              className: HeaderStyles$Savvy.header
            }, React.createElement("h2", {
                  className: HeaderStyles$Savvy.headerTitle,
                  onClick: (function (param) {
                      return ReasonReactRouter.push("/");
                    })
                }, "Savvy"));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
