// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var header = Css.style(/* :: */[
      Css.position(/* sticky */188263721),
      /* :: */[
        Css.top(Css.px(0)),
        /* [] */0
      ]
    ]);

var headerTitle = Css.style(/* :: */[
      Css.margin(Css.px(0)),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* [] */0
      ]
    ]);

export {
  header ,
  headerTitle ,
  
}
/* header Not a pure module */
