// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Stream from "bs-platform/lib/es6/stream.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";
import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

function array(arrayList) {
  return Stream.from((function (i) {
                var item;
                try {
                  item = Caml_array.caml_array_get(arrayList, i);
                }
                catch (raw_exn){
                  var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                  if (exn[0] === Caml_builtin_exceptions.invalid_argument) {
                    if (exn[1] === "index out of bounds") {
                      return ;
                    } else {
                      throw exn;
                    }
                  } else {
                    throw exn;
                  }
                }
                return Caml_option.some(item);
              }));
}

export {
  array ,
  
}
/* No side effect */
