// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Colors$Savvy from "../../styles/Colors.bs.js";
import * as Css_AtomicTypes from "bs-css/src/Css_AtomicTypes.js";

var questionText = Css.style(/* :: */[
      Css.textAlign(Css.center),
      /* [] */0
    ]);

var questions = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.alignItems(/* center */98248149),
          /* :: */[
            Css.justifyContent(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var question = Css.style(/* :: */[
      Css.margin(Css.px(5)),
      /* :: */[
        Css.padding(Css.px(25)),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.cursor(/* pointer */-786317123),
            /* :: */[
              Css.border(Css.px(2), Css.solid, Css_AtomicTypes.Color.hex(Colors$Savvy.lightblue)),
              /* :: */[
                Css.borderRadius(Css.px(10)),
                /* :: */[
                  Css.textAlign(Css.center),
                  /* :: */[
                    Css.fontSize(Css.px(24)),
                    /* :: */[
                      Css.fontWeight(Css.bold),
                      /* :: */[
                        Css.hover(/* :: */[
                              Css.backgroundColor(Css_AtomicTypes.Color.hex(Colors$Savvy.darkerIndigo)),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var selectedQuestion = Css.style(/* :: */[
      Css.margin(Css.px(5)),
      /* :: */[
        Css.padding(Css.px(25)),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.cursor(/* pointer */-786317123),
            /* :: */[
              Css.border(Css.px(2), Css.solid, Css_AtomicTypes.Color.hex(Colors$Savvy.red)),
              /* :: */[
                Css.borderRadius(Css.px(10)),
                /* :: */[
                  Css.textAlign(Css.center),
                  /* :: */[
                    Css.fontSize(Css.px(24)),
                    /* :: */[
                      Css.fontWeight(Css.bold),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var correctQuestion = Css.style(/* :: */[
      Css.margin(Css.px(5)),
      /* :: */[
        Css.padding(Css.px(25)),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.cursor(/* pointer */-786317123),
            /* :: */[
              Css.border(Css.px(2), Css.solid, Css.green),
              /* :: */[
                Css.borderRadius(Css.px(10)),
                /* :: */[
                  Css.textAlign(Css.center),
                  /* :: */[
                    Css.fontSize(Css.px(24)),
                    /* :: */[
                      Css.fontWeight(Css.bold),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  questionText ,
  questions ,
  question ,
  selectedQuestion ,
  correctQuestion ,
  
}
/* questionText Not a pure module */
