// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var questions = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.alignItems(/* center */98248149),
          /* :: */[
            Css.justifyContent(/* center */98248149),
            /* [] */0
          ]
        ]
      ]
    ]);

var question = Css.style(/* :: */[
      Css.margin(Css.px(5)),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* :: */[
          Css.fontSize(Css.px(24)),
          /* :: */[
            Css.fontWeight(Css.bold),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  questions ,
  question ,
  
}
/* questions Not a pure module */
