// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function Question(Props) {
  var currentQuestion = Props.currentQuestion;
  var nextQuestion = Props.nextQuestion;
  return React.createElement("div", undefined, Belt_Option.mapWithDefault(currentQuestion, null, (function (currentQuestion) {
                    return React.createElement("h1", {
                                dangerouslySetInnerHTML: {
                                  __html: currentQuestion[/* question */3]
                                }
                              });
                  })), Belt_Option.mapWithDefault(currentQuestion, null, (function (currentQuestion) {
                    var answers_000 = currentQuestion[/* correctAnswer */4];
                    var answers_001 = currentQuestion[/* incorretAnswers */5];
                    var answers = /* :: */[
                      answers_000,
                      answers_001
                    ];
                    return $$Array.of_list(List.map((function (answer) {
                                      return React.createElement("p", {
                                                  key: answer,
                                                  onClick: (function (param) {
                                                      return Curry._1(nextQuestion, /* () */0);
                                                    }),
                                                  dangerouslySetInnerHTML: {
                                                    __html: answer
                                                  }
                                                });
                                    }), answers));
                  })));
}

var make = Question;

export {
  make ,
  
}
/* react Not a pure module */
