// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var quizContext = /* record */[
  /* token */"",
  /* questions : [] */0
];

var context = React.createContext(quizContext);

function useQuiz(param) {
  return React.useContext(context);
}

export {
  quizContext ,
  context ,
  useQuiz ,
  
}
/* context Not a pure module */
