// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MakeStream$Savvy from "../utils/MakeStream.bs.js";

var quizContext_000 = /* state : record */[
  /* token */"",
  /* questions : array */[],
  /* quizStream */MakeStream$Savvy.array(/* array */[]),
  /* categories : array */[],
  /* numberOfQuestions */0,
  /* quizDifficulty */"any",
  /* quizType */"any",
  /* fetchingQuestions */false
];

function quizContext_001(param) {
  return /* () */0;
}

var quizContext = /* record */[
  quizContext_000,
  quizContext_001
];

var context = React.createContext(quizContext);

function useQuiz(param) {
  return React.useContext(context);
}

export {
  quizContext ,
  context ,
  useQuiz ,
  
}
/* quizContext Not a pure module */
