// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as QuizContext$Savvy from "./QuizContext.bs.js";

var make = QuizContext$Savvy.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

export {
  make ,
  makeProps ,
  
}
/* make Not a pure module */
