// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Category$Savvy from "./components/Category/Category.bs.js";
import * as AppStyles$Savvy from "./AppStyles.bs.js";
import * as QuizContext$Savvy from "./context/QuizContext.bs.js";

function App(Props) {
  var quizContext = QuizContext$Savvy.useQuiz(/* () */0);
  React.useEffect((function () {
          Curry._1(quizContext[/* dispatch */1], /* ClearContext */1);
          return ;
        }), /* array */[]);
  return React.createElement("div", {
              className: AppStyles$Savvy.container
            }, $$Array.map((function (category) {
                    return React.createElement(Category$Savvy.make, {
                                category: category,
                                key: String(category[/* id */0])
                              });
                  }), quizContext[/* state */0][/* categories */3]));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
