// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Category$Savvy from "./components/Category/Category.bs.js";
import * as Categories$Savvy from "./components/Categories/Categories.bs.js";

function App(Props) {
  return React.createElement(Categories$Savvy.make, {
              children: (function (categoryList) {
                  return $$Array.map((function (category) {
                                return React.createElement(Category$Savvy.make, {
                                            category: category,
                                            key: String(category[/* id */0])
                                          });
                              }), categoryList);
                })
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
