// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Root$Savvy from "./Root.bs.js";

var globalFont = Css.fontFace("MontserratMedium", /* :: */[
      Css.url("./src/fonts/Montserrat-Light.otf"),
      /* [] */0
    ], undefined, undefined, /* () */0);

Css.$$global("html", /* :: */[
      Css.boxSizing(Css.borderBox),
      /* :: */[
        Css.selector("*, *:before, *:after", /* :: */[
              Css.boxSizing(Css.inherit_),
              /* :: */[
                Css.fontFamily(globalFont),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

Css.$$global("body", /* :: */[
      Css.fontFamily(globalFont),
      /* :: */[
        Css.margin(Css.px(0)),
        /* [] */0
      ]
    ]);

Css.$$global("#app", /* :: */[
      Css.margin(Css.px(25)),
      /* [] */0
    ]);

ReactDOMRe.renderToElementWithId(React.createElement(Root$Savvy.make, { }), "app");

export {
  globalFont ,
  
}
/* globalFont Not a pure module */
