// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Types$Savvy from "./types/Types.bs.js";
import * as Router$Savvy from "./Router.bs.js";
import * as MakeStream$Savvy from "./utils/MakeStream.bs.js";
import * as QuizProvider$Savvy from "./context/QuizProvider.bs.js";

var initialState_001 = /* questions : array */[];

var initialState_002 = /* quizStream */MakeStream$Savvy.array(/* array */[]);

var initialState = /* record */[
  /* token */"",
  initialState_001,
  initialState_002,
  /* numberOfQuestions */0,
  /* quizDifficulty */"any",
  /* quizType */"any"
];

function reducer(state, action) {
  if (typeof action === "number") {
    return /* record */[
            /* token */state[/* token */0],
            /* questions */state[/* questions */1],
            /* quizStream */MakeStream$Savvy.array(state[/* questions */1]),
            /* numberOfQuestions */state[/* numberOfQuestions */3],
            /* quizDifficulty */state[/* quizDifficulty */4],
            /* quizType */state[/* quizType */5]
          ];
  } else {
    switch (action.tag | 0) {
      case /* SetNumberOfQuestions */0 :
          return /* record */[
                  /* token */state[/* token */0],
                  /* questions */state[/* questions */1],
                  /* quizStream */state[/* quizStream */2],
                  /* numberOfQuestions */action[0],
                  /* quizDifficulty */state[/* quizDifficulty */4],
                  /* quizType */state[/* quizType */5]
                ];
      case /* SetQuizDifficulty */1 :
          return /* record */[
                  /* token */state[/* token */0],
                  /* questions */state[/* questions */1],
                  /* quizStream */state[/* quizStream */2],
                  /* numberOfQuestions */state[/* numberOfQuestions */3],
                  /* quizDifficulty */action[0],
                  /* quizType */state[/* quizType */5]
                ];
      case /* SetQuizType */2 :
          return /* record */[
                  /* token */state[/* token */0],
                  /* questions */state[/* questions */1],
                  /* quizStream */state[/* quizStream */2],
                  /* numberOfQuestions */state[/* numberOfQuestions */3],
                  /* quizDifficulty */state[/* quizDifficulty */4],
                  /* quizType */action[0]
                ];
      case /* SetQuestions */3 :
          return /* record */[
                  /* token */state[/* token */0],
                  /* questions */action[0],
                  /* quizStream */state[/* quizStream */2],
                  /* numberOfQuestions */state[/* numberOfQuestions */3],
                  /* quizDifficulty */state[/* quizDifficulty */4],
                  /* quizType */state[/* quizType */5]
                ];
      case /* SetToken */4 :
          return /* record */[
                  /* token */action[0],
                  /* questions */state[/* questions */1],
                  /* quizStream */state[/* quizStream */2],
                  /* numberOfQuestions */state[/* numberOfQuestions */3],
                  /* quizDifficulty */state[/* quizDifficulty */4],
                  /* quizType */state[/* quizType */5]
                ];
      
    }
  }
}

function Root(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var contextValue_000 = /* state */match[0];
  var contextValue = /* record */[
    contextValue_000,
    /* dispatch */dispatch
  ];
  React.useEffect((function () {
          fetch("https://opentdb.com/api_token.php?command=request").then((function (res) {
                    return res.json();
                  })).then((function (json) {
                  var tokenResponse = Types$Savvy.RequestToken.decode(json);
                  Curry._1(dispatch, /* SetToken */Block.__(4, [tokenResponse[/* token */2]]));
                  return Promise.resolve(/* () */0);
                }));
          return ;
        }), ([]));
  return React.createElement(QuizProvider$Savvy.make, QuizProvider$Savvy.makeProps(contextValue, React.createElement(Router$Savvy.make, { }), /* () */0));
}

var make = Root;

export {
  initialState ,
  reducer ,
  make ,
  
}
/* initialState Not a pure module */
