// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Router$Savvy from "./Router.bs.js";
import * as APIDecode$Savvy from "./apiDecode/APIDecode.bs.js";
import * as QuizProvider$Savvy from "./context/QuizProvider.bs.js";

var intialState = /* record */[
  /* token */"",
  /* questions : [] */0
];

function reducer(initialState, action) {
  return /* record */[
          /* token */action[0],
          /* questions */initialState[/* questions */1]
        ];
}

function Root(Props) {
  var match = React.useReducer(reducer, intialState);
  var dispatch = match[1];
  React.useEffect((function () {
          fetch("https://opentdb.com/api_token.php?command=request").then((function (res) {
                    return res.json();
                  })).then((function (json) {
                  var tokenResponse = APIDecode$Savvy.RequestToken.decode(json);
                  Curry._1(dispatch, /* SetToken */[tokenResponse[/* token */2]]);
                  return Promise.resolve(/* () */0);
                }));
          return ;
        }), ([]));
  return React.createElement(QuizProvider$Savvy.make, QuizProvider$Savvy.makeProps(match[0], React.createElement(Router$Savvy.make, { }), /* () */0));
}

var make = Root;

export {
  intialState ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
