// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App$Codex from "./App.bs.js";
import * as General$Codex from "./views/General.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  if (match && match[0] === "general" && !match[1]) {
    return React.createElement(General$Codex.make, { });
  }
  return React.createElement(App$Codex.make, { });
}

var make = Router;

export {
  make ,
  
}
/* react Not a pure module */
